### PR TITLE
Update pr-checks.yml

### PR DESCRIPTION
**Pull request by aeisenberg**

### CODE REVIEW

**Review by adityasharad — DISMISSED** [review]
Tough review 😁

**Comment by aeisenberg** [comment]
I can't figure this out. My guess is that there's some sort of unprintable char getting returned that is breaking things. But not sure why it's happening on CI only.

It's not really worth spending more time on this, so I think I'll just remove the failing test and getting things through.

**Comment by AlexanderBrevig** [comment]
I think I found the solution!

`head -n 1` closes the pipe, replace with `sed '1!d'` and it works :) 

```bash
          LATEST_NIGHTLY_TAG="$(gh api "repos/dsp-testing/codeql-cli-nightlies/releases" --jq ".[] | select(.draft == false) | .tag_name" | sed '1!d')"
```

```bash
          LATEST_NIGHTLY_VERSION="$(gh api "repos/dsp-testing/codeql-cli-nightlies/releases" --jq '.[] | select(.draft == false) | .body '| sed '1!d' | awk '{print $4}')"

**Comment by AlexanderBrevig** [comment]
I added the fix to #27

**Comment by aeisenberg** [comment]
Rebasing on #27, which should be running.

**Review by angelapwen — APPROVED** [review]

**Pull request merged**
